server:
  port: 8090
  session-timeout: 30
spring:
  thymeleaf:
    mode: HTML5
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: utf-8
  profiles:
    active: local
mybatis:
  typeAliasesPackage: com.highrock.*.bean
  mapperLocations: classpath:mappers/*.xml
security:
  basic:
    enable: true
  user:
    name: user
    password: pass
log:
  path: /usr/api/logs
  level: info

backEndApi:
  auth:
    user: user
    password: pass
  url:
    insertOrder: /order/
    updateOrder: /order/addr
---
spring:
  profiles: local
  datasource:
    url : jdbc:mysql://localhost:3306/72craft_prod
    username : earthling
    password : 4wsgfxt87oguykjo7ilgubjhydthcg
    driverClassName : com.mysql.jdbc.Driver
  earthlingAuth:
    user: abc@456.com
    password: password
  earthlingApiUrl:
    root: https://abc.def
    orderStatus: /Order_Status_To_Customer
  backEndApiUrl: http://172.16.1.48:8090
  s3LogBucket: highrock-api-log-stage
\




